"""Create inactive users and users without characters tables

Revision ID: 375c233ea8c9
Revises: 5d2afdd9590b
Create Date: 2020-02-17 02:12:56.019871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375c233ea8c9'
down_revision = '5d2afdd9590b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inactive_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('sended_date', sa.DateTime(), nullable=False),
    sa.Column('server_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_without_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('sended_date', sa.DateTime(), nullable=False),
    sa.Column('server_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_without_characters')
    op.drop_table('inactive_users')
    # ### end Alembic commands ###
