"""Added status field for inactive users and users without characters tables

Revision ID: 94bf3f5078a2
Revises: 375c233ea8c9
Create Date: 2020-02-17 02:30:01.635274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94bf3f5078a2'
down_revision = '375c233ea8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inactive_users', sa.Column('status', sa.Boolean(), nullable=False))
    op.add_column('users_without_characters', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_without_characters', 'status')
    op.drop_column('inactive_users', 'status')
    # ### end Alembic commands ###
